server:
  port: 3344

spring:
  application:
    name: micro-service-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Itcc-svg/micro_service_cloud_config.git
          username: 384406323@qq.com
          password: xinnian.0023
